services:
  micro_02:
    build:
      args:
        user: lucas
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    restart: unless-stopped
    networks:
      - microservices02
  
  #nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - microservices02
  
  # queue
  queue:
    build:
      args:
        user: lucas
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    restart: unless-stopped
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - microservices02
  
  #mysql micro 02
  db_micro_02:
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - 3343:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - microservices02

  # redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - microservices02

networks:
  microservices02:
    driver: bridge
